const fs = require('fs');
const path = require('path');

// Determine provider from DATABASE_URL
const dbUrl = process.env.DATABASE_URL || '';
let provider;

if (dbUrl.startsWith('postgresql://') || dbUrl.startsWith('postgres://')) {
  provider = 'postgresql';
} else if (dbUrl.startsWith('file:')) {
  provider = 'sqlite';
} else {
  provider = 'sqlite';
}

// Update migration_lock.toml
const lockPath = path.join(__dirname, '..', 'prisma', 'migrations', 'migration_lock.toml');
const lockContent = `# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "${provider}"`;

fs.writeFileSync(lockPath, lockContent);
console.log(`Updated migration_lock.toml with provider=${provider}`);

// Fix migration SQL for the detected provider
const migrationsDir = path.join(__dirname, '..', 'prisma', 'migrations');
if (fs.existsSync(migrationsDir)) {
  const migrationFolders = fs.readdirSync(migrationsDir).filter(f => {
    const fullPath = path.join(migrationsDir, f);
    return fs.statSync(fullPath).isDirectory();
  });

  migrationFolders.forEach(folder => {
    const sqlPath = path.join(migrationsDir, folder, 'migration.sql');
    if (fs.existsSync(sqlPath)) {
      let sql = fs.readFileSync(sqlPath, 'utf-8');
      
      if (provider === 'postgresql' && sql.includes('AUTOINCREMENT')) {
        // Convert SQLite to PostgreSQL
        sql = sql
          .replace(/INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT/g, 'SERIAL PRIMARY KEY')
          .replace(/DATETIME/g, 'TIMESTAMP(3)');
        fs.writeFileSync(sqlPath, sql);
        console.log(`Converted ${folder}/migration.sql to PostgreSQL format`);
      } else if (provider === 'sqlite' && sql.includes('SERIAL')) {
        // Convert PostgreSQL to SQLite
        sql = sql
          .replace(/SERIAL PRIMARY KEY/g, 'INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT')
          .replace(/TIMESTAMP\(3\)/g, 'DATETIME');
        fs.writeFileSync(sqlPath, sql);
        console.log(`Converted ${folder}/migration.sql to SQLite format`);
      }
    }
  });
}
